<?php
$_['heading_title'] = 'ProBG AI Tools';

$_['text_extension'] = 'Extensions';
$_['text_success'] = 'ProBG AI Tools settings have been saved successfully!';
$_['text_edit'] = 'ProBG AI Tools Settings';
$_['text_enabled'] = 'Enabled';
$_['text_disabled'] = 'Disabled';
$_['text_yes'] = 'Yes';
$_['text_no'] = 'No';
$_['text_ai_catalog_url'] = 'AI Catalog';

$_['tab_general'] = 'General';
$_['tab_ai_sitemap'] = 'AI Sitemap';
$_['tab_ai_catalog'] = 'AI Catalog';
$_['tab_llms'] = 'LLMS';
$_['tab_products_graph'] = 'Products Graph';
$_['tab_advanced'] = 'Advanced';

$_['entry_status'] = 'Status';
$_['entry_product_limit'] = 'Product limit';
$_['entry_site_description'] = 'AI description for llms.txt';
$_['entry_products'] = 'Products';
$_['entry_categories'] = 'Categories';
$_['entry_brands'] = 'Brands';
$_['entry_ai_sitemap'] = 'AI Sitemap';
$_['entry_ai_sitemap_url'] = 'AI Sitemap URL';
$_['entry_llms_txt'] = 'llms.txt';
$_['entry_llms_json'] = 'llms.json';
$_['entry_llms_full'] = 'llms-full.txt';
$_['entry_ai_catalog'] = 'AI Catalog';
$_['entry_ai_policy'] = 'AI Access Policy';
$_['entry_products_graph'] = 'Products Graph';
$_['entry_search_index'] = 'Search Index';
$_['entry_semantic_graph'] = 'Semantic Graph';
$_['entry_htaccess'] = '.htaccess rules';

$_['help_status'] = 'Enables or disables all public resources generated by ProBG AI Tools.';
$_['help_product_limit'] = '0 = all products. A positive number limits products across all generated resources.';
$_['help_site_description'] = 'A short store description for AI models. The store Meta Description is used when left empty.';
$_['help_products'] = 'Includes products in generated AI resources.';
$_['help_categories'] = 'Includes categories in generated AI resources.';
$_['help_brands'] = 'Includes brands in generated AI resources.';
$_['help_ai_sitemap'] = 'Enables or disables the standard XML ai-sitemap.xml file.';
$_['help_llms_txt'] = 'Enables or disables the public llms.txt file.';
$_['help_llms_json'] = 'Enables or disables the public llms.json file.';
$_['help_llms_full'] = 'Enables or disables the extended llms-full.txt file.';
$_['help_ai_catalog'] = 'Generates ai-catalog.json with structured store data.';
$_['help_ai_policy'] = 'Generates an informational ai-policy.txt file. Actual crawler access is controlled by robots.txt.';
$_['help_products_graph'] = 'Generates products.graph.json with product → category and product → brand relations.';
$_['help_search_index'] = 'Generates search-index.json with normalized keywords and search-term combinations.';
$_['help_semantic_graph'] = 'Generates semantic.graph.json with semantic relations between products, categories, and brands.';
$_['help_htaccess'] = 'Add these rules to .htaccess before the main OpenCart SEO RewriteRule.';

$_['button_save'] = 'Save';
$_['button_cancel'] = 'Cancel';

$_['text_htaccess_rule'] = 'RewriteRule ^ai-sitemap\.xml$ index.php?route=extension/feed/probg_ai_tools/sitemap [L,QSA]\nRewriteRule ^llms\.txt$ index.php?route=extension/feed/probg_ai_tools/llms [L,QSA]\nRewriteRule ^llms\.json$ index.php?route=extension/feed/probg_ai_tools/json [L,QSA]\nRewriteRule ^llms-full\.txt$ index.php?route=extension/feed/probg_ai_tools/full [L,QSA]\nRewriteRule ^products\.graph\.json$ index.php?route=extension/feed/probg_ai_tools/graph [L,QSA]\nRewriteRule ^ai-catalog\.json$ index.php?route=extension/feed/probg_ai_tools/catalog [L,QSA]\nRewriteRule ^ai-policy\.txt$ index.php?route=extension/feed/probg_ai_tools/policy [L,QSA]\nRewriteRule ^search-index\.json$ index.php?route=extension/feed/probg_ai_tools/search [L,QSA]\nRewriteRule ^semantic\.graph\.json$ index.php?route=extension/feed/probg_ai_tools/semantic [L,QSA]';

$_['error_permission'] = 'You do not have permission to modify ProBG AI Tools!';
$_['error_product_limit'] = 'The product limit must be a non-negative integer.';
